// Generated by CoffeeScript 2.3.1
(function() {
  var _, data, moment, ohlc, test;

  require('source-map-support').install();

  _ = require('lodash');

  moment = require('moment');

  ({test} = require('ava'));

  ohlc = require('../');

  data = require('../sample/coinmarketcap.json');

  test('coinmarketcap format', function(t) {
    var opts, prices;
    opts = {
      inputDateFormat: 'MMM DD, YYYY'
    };
    prices = ohlc(data, opts).value();
    return t.deepEqual(prices[0], {
      Close: 7078.5,
      Date: '2017-11-02',
      High: 7367.33,
      Low: 6758.72,
      Open: 6777.77,
      Volume: 4653770240,
      'Market Cap': 112909656064
    });
  });

  test('coinmarketcap', function(t) {
    var opts, prices;
    opts = {
      INPUTDATEFORMAT: 'MMM DD, YYYY'
    };
    prices = ohlc(data, opts).sma(5, 25, 75).value();
    return t.snapshot(prices);
  });

  test('validate', function(t) {
    var errors, opts;
    opts = {
      INPUTDATEFORMAT: 'MMM DD, YYYY'
    };
    errors = ohlc(data, opts).validate();
    // t.log errors
    return t.pass();
  });

}).call(this);
