// Generated by CoffeeScript 2.3.1
(function() {
  var _, data, moment, ohlc, test;

  require('source-map-support').install();

  _ = require('lodash');

  moment = require('moment');

  ({test} = require('ava'));

  ohlc = require('../');

  data = require('../sample/quandlSample.json');

  test('validate', function(t) {
    var inValid;
    inValid = ohlc(data).validate();
    t.is(inValid.length, 2);
    return t.pass();
  });

}).call(this);
