// Generated by CoffeeScript 2.3.1
(function() {
  var baseConfig, merge;

  merge = require('webpack-merge');

  baseConfig = require('./webpack.config.base.js');

  module.exports = merge(baseConfig, {
    mode: 'production'
  });

}).call(this);
