// Generated by CoffeeScript 2.3.1
(function() {
  var _, modify;

  _ = require('../node_modules/lodash/lodash.min.js');

  module.exports = modify = {
    zero: function() {
      var items, refClose;
      items = [];
      refClose = null;
      this.items.forEach(function(item) {
        var newItem;
        if (refClose && item.Volume === 0) {
          newItem = _.cloneDeep(item);
          newItem.Open = refClose;
          newItem.High = refClose;
          newItem.Low = refClose;
          newItem.Close = refClose;
          items.push(newItem);
        } else {
          refClose = item.Close;
          items.push(item);
        }
      });
      this.items = items;
      return this;
    },
    all: function() {
      modify.zero.call(this);
      return this;
    }
  };

}).call(this);
