// Generated by CoffeeScript 2.3.1
(function() {
  var Big, _, util;

  Big = require('big.js');

  _ = require('../node_modules/lodash/lodash.min.js');

  module.exports = util = {
    decimalPlace: function(num) {
      var arr, e, m, md, me, str;
      if (!_.isNumber(num)) {
        return 0;
      } else if (Number.isNaN(num)) {
        return 0;
      } else {
        str = num.toString();
        if (str.includes('e-')) {
          arr = str.split('e-');
          m = parseFloat(arr[0]);
          e = parseFloat(arr[1]);
          md = m.toString().split('.');
          me = md.length === 1 ? 0 : md[1].length;
          return me + e;
        } else if (str.includes('e+')) {
          arr = str.split('e+'); //[1.23, 1]
          m = parseFloat(arr[0]);
          e = parseFloat(arr[1]);
          md = m.toString().split('.'); //[1,23]
          me = md.length === 1 ? 0 : md[1].length;
          if (me - e <= 0) {
            return 0;
          } else {
            return me - e;
          }
        } else {
          arr = str.split('.');
          if (arr.length >= 2) {
            return arr[1].length;
          } else {
            return 0;
          }
        }
      }
    }
  };

}).call(this);
