// Generated by CoffeeScript 2.3.1
(function() {
  // require('source-map-support').install()
  var Big, _, arrayData, coffee, decimalPlace, moment, objData, ohlc;

  _ = require('lodash');

  moment = require('moment');

  ohlc = require('../../');

  objData = require('../../sample/objData.json');

  arrayData = require('../../sample/arrayData.json');

  ({decimalPlace} = require('../lib/util'));

  Big = require('big.js');

  coffee = require('coffeescript');

  test('coffee', function() {
    return expect(coffee.compile('console.log hoge', {
      bare: true
    })).toBe('console.log(hoge);\n');
  });

}).call(this);
